"""empty message

Revision ID: 01c2eadd88da
Revises: e7ab80d50793
Create Date: 2018-07-19 20:57:04.906559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01c2eadd88da'
down_revision = 'e7ab80d50793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('date', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Entry')
    # ### end Alembic commands ###
